In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2,3],[4,5,6]])

In [4]:
print("Array is of type : ",type(arr))
print("No. of dimensions : ",arr.ndim)
print("Shape of array : ",arr.shape)
print("Size of array : ",arr.size)
print("Array stores elements of type : ",arr.dtype)

Array is of type :  <class 'numpy.ndarray'>
No. of dimensions :  2
Shape of array :  (2, 3)
Size of array :  6
Array stores elements of type :  int32


In [9]:
b= np.array((1,6,7))

In [10]:
print("array created using passed tuple : \n",b)

array created using passed tuple : 
 [1 6 7]


In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
f=np.arange(0,30,5)
g=np.linspace(0,5,10)

In [16]:
print(f)

[ 0  5 10 15 20 25]


In [17]:
print(g)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [18]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
newarr=arr.reshape((4,3))
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])