# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [36]:
print(np.__version__)
np.__config__.show()

1.18.2
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10

In [9]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [5]:
x=np.array([1,2,3])
x.size*x.itemsize

12

#### 5.  How to get the documentation of the numpy add function from the command line? 

In [ ]:
python -c "import numpy; numpy.info(numpy.add)"

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [8]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49

In [11]:
vect=np.arange(10,50)
vect

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last)

In [15]:
v=np.arange(1,6)
print(v)
rev=v[::-1]
print(rev)

[1 2 3 4 5]
[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [18]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [22]:
x=np.array([1,2,0,0,4,0])
print(np.nonzero(x))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [23]:
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [24]:
x=np.random.random((3,3,3))
print(x)

[[[0.64108954 0.40723049 0.91545475]
  [0.70739029 0.94196267 0.63266506]
  [0.93390371 0.16222093 0.52976114]]

 [[0.62820196 0.40455951 0.2716557 ]
  [0.09980524 0.64719207 0.66468609]
  [0.7295291  0.80977189 0.31249045]]

 [[0.2370368  0.20117414 0.00358422]
  [0.69362648 0.28288426 0.21545895]
  [0.27038585 0.17244323 0.21898428]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
x=np.random.random((10,10))
print(x)
xmin=x.min()
xmax=x.max()
print("xmin=",xmin)
print("xmax=",xmax)

[[0.74145715 0.23723609 0.18907504 0.53026427 0.50615022 0.0755945
  0.88711562 0.83422329 0.01899708 0.55058009]
 [0.25534435 0.39738936 0.38584062 0.62745424 0.42589782 0.9439429
  0.05252798 0.91444432 0.50198344 0.84109201]
 [0.31469658 0.05154642 0.97225694 0.9549458  0.14980796 0.57871694
  0.45520794 0.61722866 0.50894147 0.3514117 ]
 [0.93400768 0.4286068  0.85958031 0.86564661 0.45512868 0.58695444
  0.62286232 0.73060467 0.64266074 0.17209423]
 [0.63917377 0.70266632 0.35680933 0.59143066 0.99257024 0.36441417
  0.03725221 0.51491774 0.91470331 0.65273978]
 [0.46104867 0.61568322 0.65840704 0.41237375 0.63227865 0.59569437
  0.61718568 0.55390472 0.9578811  0.49080331]
 [0.74647045 0.38186127 0.7715528  0.84540596 0.38201785 0.86276965
  0.54046549 0.29415781 0.23144604 0.77394699]
 [0.66735959 0.24352888 0.89888974 0.27107287 0.80589301 0.00381739
  0.67428719 0.03444869 0.41287345 0.36602164]
 [0.67982238 0.0104812  0.93224573 0.13102563 0.51948875 0.28718823
  0.99296331 0

#### 14. Create a random vector of size 30 and find the mean value

In [28]:
x=np.random.random(30)
print(x)
x.mean()

[0.41401905 0.58244064 0.38634275 0.99207378 0.45149205 0.05901461
 0.91171136 0.57193053 0.81291474 0.69427393 0.04904314 0.98276985
 0.87529788 0.05117305 0.2868612  0.23343066 0.38596449 0.86891302
 0.48516875 0.76940235 0.90853286 0.83639902 0.7870777  0.77385878
 0.89140699 0.63203094 0.76029134 0.94072197 0.95037027 0.85131773]


0.6398748475165383

#### 15. Create a 2d array with 1 on the border and 0 inside

In [29]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [31]:
x=np.ones((4,4))
x=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
nan
false
false
nan
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
z=np.diag(1+np.arange(4),k=-1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [33]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
